version: "3.3"
services:
  redis:
    image: redis
  mongodb:
    image: mongo
    environment:
      - ES_HEAP_SIZE=2g
      - MAX_MAP_COUNT=262144
      - ELASTICSEARCH_START=1
      - LOGSTASH_START=0
      - KIBANA_START=0
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "4718:4718"
    deploy:
      resources:
        limits:
          memory: 4g
  mariadb:
    image: mariadb/server:10.5
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
